
twilio:
  account_sid: B5YNgQEGTRo5dbxisAVNx9YUS+5rZRumxD9rZSGw8XccpZ44gdZIm87BzAy2ze7n
  auth_token: cPwQOKEUyCiaZCDLekKM5/gz/Pc5ztlm2e92V1tHtHvMrRaJzaELIdDenvg9Z04C
  trial_number: yAwCaVySHxsyxXhkhfz7uw==